### ISSUE TITLE
Generate Target interface methods

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane-tools#14]
### What problem are you facing?

The new `Target` interface was implemented as part of https://github.com/crossplaneio/crossplane-runtime/pull/103, but the methods required to satisfy its embedded interfaces are not generated by `angryjet`.

### How could Crossplane help solve your problem?

While there is only one implementation of the `Target` interface at this time (`KubernetesTarget`), it would be helpful and more consistent with other Crossplane interfaces if we generated the required methods automatically.

**Comment by negz** [comment]
Closing this as Target is now slated for removal per https://github.com/crossplane/crossplane/issues/1755
